### ISSUE TITLE
Binary artifacts should not be included

### ISSUE THREAD

**Issue by gigamonster256** [akshatnerella/pyladdersim#2]
Binary cache artifacts and development directories such as `__pycache__` and `venv` should be added to a .gitignore.

See the [default github python gitignore](https://github.com/github/gitignore/blob/76739a38b56907118c5a880d63250c99d5690a5a/Python.gitignore)  for an example of a good gitignore for python projects.

**Comment by akshatnerella** [comment]
fixed. thanks!

**Comment by gigamonster256** [comment]
The cache folders are still there
